### ISSUE TITLE
在学习这套 代码

### ISSUE THREAD

**Issue by zuumau** [moyuanhua/jike-wepy-eggjs#1]
请问这套代码 完整吗

在 login 方法种，  直接从  this.ctx.state.user.data._id;   从 ctx.stste 中读取用户信息
我有两疑问， 请指导一下
1.   ctx.state.user  是什么时候存进去的。 
2.   小程序没有 cookie ，ctx.state 可以自动识别用户吗？
```
        async login() {
            const {
                ctx,
                service,
            } = this;
            const user = await service.user.getuserinfobyself();
            const res = {
                token: await service.actionToken.apply(user._id, user.openid),
                userinfo: user.userinfo ? user.userinfo : false,
            };
            ctx.helper.success(ctx, res);
        }
```

**Comment by moyuanhua** [comment]
@zuumau 你好， 这套代码是完整的，是从两个成熟项目中剥离出来的基础框架。
1. ctx.state.user 是从jwt中解析出来的。 在router中使用app.jwt的中间件的时候，在这个中间件中解析并且放在这个变量里面。 使用的插件是 egg-jwt .
2. 小程序是没有cookie ， 所以我们的token是存在 storage里面的。 在每次请求的时候在头部带上 token， 交由 egg-jwt 解析获得用户数据， 如果用户登录时间超时（身份失效）。 egg-jwt会自动返回错误, 这个时候在前端从新鉴权即可。

**Comment by zuumau** [comment]
谢谢
